### ISSUE TITLE
为什么我一加入这个gem 在启动的时候就报如下错误呢？

### ISSUE THREAD

**Issue by zhenweiwang1990** [beenhero/omniauth-qq#2]
是rails应用，weibo的oauth2 google的oauth2都没问题，我一加入qq的这个gem就启动不了。
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.2.4/lib/bundler/runtime.rb:74:in `require': cannot load such file -- omniauth/qq (LoadError)

**Comment by beenhero** [comment]
Hi,
你 Omniauth 什么版本? 我的还是老的 1.0.3, 可以正常工作.
这个库, 好久没有更新了. 可能Omniauth 更新过strategy了, 需要做相应的改动.

**Comment by zhenweiwang1990** [comment]
目前是1.1.4

**Comment by beenhero** [comment]
刚修复了一个之前埋藏的bug, 你更新下gem 到0.3.0再试下.
